{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f02d9bfc",
   "metadata": {},
   "outputs": [],
   "source": [
    "from multiprocessing import Pool\n",
    "from requests import get\n",
    "from json import dump\n",
    "from os import getcwd\n",
    "from os import path\n",
    "from os import mkdir\n",
    "from tqdm import tqdm\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "## FUNCTIONS\n",
    "def getRawHTML(link):\n",
    "    \n",
    "    r = get(link, headers={'User-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0'})\n",
    "    c = r.content\n",
    "    soup = BeautifulSoup(c, \"html.parser\")\n",
    "    \n",
    "    return soup\n",
    "\n",
    "def retrieveServiceData(data):\n",
    "    \n",
    "    all = data.find_all('table', {\"class\": \"typetable\"})\n",
    "    \n",
    "    serviceArr = []\n",
    "    for item in all[0].find_all('tr'):\n",
    "        serviceObj = {}\n",
    "        \n",
    "        try:\n",
    "            service = item.find_all('td')[0].find('a', {\"class\": \"link\"}).text\n",
    "            serviceObj['service'] = service\n",
    "        except:\n",
    "            service = 'NA'\n",
    "        \n",
    "        try:\n",
    "            desc = item.find_all('td')[1].text.replace(\"\\n\", \"\")\n",
    "            serviceObj['description'] = desc\n",
    "        except:\n",
    "            desc = 'NA'\n",
    "        \n",
    "        try:\n",
    "            postStr = item.find('a', {\"class\": 'link'})['href']\n",
    "            link = base_url + postStr\n",
    "            serviceObj['link'] = link\n",
    "        except:\n",
    "            link = 'NA'\n",
    "    \n",
    "        if serviceObj:\n",
    "            serviceArr.append(serviceObj)\n",
    "    \n",
    "    fileDir = dirPath +'/service'\n",
    "    if not path.exists(fileDir):\n",
    "        mkdir(fileDir)\n",
    "        \n",
    "    with open(path.join(fileDir, '') + 'service.json', 'w+') as outfile:\n",
    "        dump(serviceArr, outfile)\n",
    "        \n",
    "    return serviceArr\n",
    "\n",
    "def retrieveOperationData(link, index):\n",
    "    \n",
    "    data = getRawHTML(link)\n",
    "    \n",
    "    all = data.find_all('table', {\"class\": \"typetable\"})\n",
    "\n",
    "    operationArr = []\n",
    "    for item in all[0].find_all('tr'):\n",
    "        operationOj = {}\n",
    "        \n",
    "        try:\n",
    "            ops = item.find_all('td')[0].find('a', {\"class\": \"link\"}).text\n",
    "            operationOj['operation'] = ops\n",
    "        except:\n",
    "            ops = 'NA'\n",
    "        \n",
    "        try:\n",
    "            desc = item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\u00a0\", \"\")\n",
    "            operationOj['description'] = desc\n",
    "        except:\n",
    "            desc = 'NA'\n",
    "        \n",
    "        try:\n",
    "            postStr = item.find('a', {\"class\": 'link'})['href']\n",
    "            link = base_url + serviceArr[index]['service'] + '/v38.2/' + postStr\n",
    "            link = link.strip()\n",
    "            operationOj['link'] = link\n",
    "        except:\n",
    "            link = 'NA'\n",
    "    \n",
    "        if operationOj:\n",
    "            operationOj['service'] = serviceArr[index]['service']\n",
    "            operationArr.append(operationOj)\n",
    "    \n",
    "    fileDir = dirPath +'/operation'\n",
    "    if not path.exists(fileDir):\n",
    "        mkdir(fileDir)\n",
    "        \n",
    "    individual_ops_target_dir = fileDir + '/'+ operationOj['service'] +'/'\n",
    "    if not path.exists(individual_ops_target_dir):\n",
    "        mkdir(individual_ops_target_dir)\n",
    "    \n",
    "    with open(path.join(individual_ops_target_dir, '') + operationOj['service'] + '.json', 'w+') as outfile:\n",
    "        dump(operationArr, outfile)\n",
    "    \n",
    "    return operationArr\n",
    "\n",
    "def retrieve(hrefName):\n",
    "    fieldsArr = []\n",
    "    for i in data:\n",
    "        for j in i.find_all('td'):\n",
    "            if j.find('a', {\"name\": hrefName}):\n",
    "                fieldsData = (j.find('table', {\"class\": 'typetable'})).find_all('tr')\n",
    "                for item in fieldsData:\n",
    "                    if len(item.find_all('td')) > 2:\n",
    "                        fieldsObj = {}\n",
    "                        try:\n",
    "                            fieldsObj['parameterName'] = item.find_all('td')[0].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['parameterName'] = 'NA'\n",
    "\n",
    "                        try:\n",
    "                            fieldsObj['type'] = item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                            if ((item.find_all('td')[1]).find('a')):\n",
    "                                if ((item.find_all('td')[1]).find('a')).get('href'): \n",
    "                                    fieldsObj[item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")] = retrieve(((item.find_all('td')[1]).find('a')).get('href')[1:])\n",
    "                        except:\n",
    "                            fieldsObj['type'] = 'NA'\n",
    "                            \n",
    "                        try:\n",
    "                            fieldsObj['cardinality'] = item.find_all('td')[2].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['cardinality'] = 'NA'\n",
    "    \n",
    "                        try:\n",
    "                            fieldsObj['description'] = item.find_all('td')[3].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['description'] = 'NA'\n",
    "                            \n",
    "                        if fieldsObj:\n",
    "                            fieldsArr.append(fieldsObj)\n",
    "    \n",
    "    return fieldsArr\n",
    "\n",
    "def retrieveFieldData(link, service, operation):\n",
    "    \n",
    "    print(\"=====================\")\n",
    "    print(link)\n",
    "    \n",
    "    rawFieldData = getRawHTML(link)    \n",
    "    ulList = rawFieldData.find_all('ul')[2]\n",
    "    requesthreflink = ((ulList.find('li')).find('a'))['href'][1:]\n",
    "    data = rawFieldData.find_all('table')[0].find_all('tr')\n",
    "    \n",
    "    xyz = retrieve(requesthreflink)\n",
    "    \n",
    "    print(\"=====================\")\n",
    "    print(service)\n",
    "    print(operation)\n",
    "    print(fileDir)\n",
    "    print(path.join(fileDir, '') + operation + \".json\")\n",
    "    fileDir = dirPath +'/operation/' + service + '/fields'\n",
    "    if not path.exists(fileDir):\n",
    "        mkdir(fileDir)\n",
    "    with open(path.join(fileDir, '') + operation + \".json\", \"w+\") as outfile:\n",
    "        dump(arr, outfile)\n",
    "        \n",
    "    return True\n",
    "\n",
    "dirPath = getcwd()\n",
    "\n",
    "base_url = \"https://community.workday.com/sites/default/files/file-hosting/productionapi/\"\n",
    "\n",
    "## Service Extraction\n",
    "rawServiceData = getRawHTML(\"https://community.workday.com/sites/default/files/file-hosting/productionapi/index.html\")\n",
    "serviceArr = retrieveServiceData(rawServiceData)\n",
    "\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    pool1 = Pool()\n",
    "    result_async = [pool1.apply_async(retrieveOperationData, args = (serviceArr[index]['link'].strip(), index, )) for index in\n",
    "                    range(len(serviceArr))]\n",
    "    \n",
    "    result_async = [result_async[id].get() for id in range(len(result_async))]\n",
    "        \n",
    "    for id in tqdm(range(len(result_async))):\n",
    "        print(\"===========================\")\n",
    "        print(result_async[id][0]['link'].strip())\n",
    "        result_async1 = [pool1.apply_async(retrieveFieldData, args = (result_async[id][index]['link'].strip(), result_async[id][index]['service'], result_async[id][index]['operation'], )) for index in\n",
    "                    range(len(result_async[id]))]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68b2ea63",
   "metadata": {},
   "outputs": [],
   "source": [
    "process = [] \n",
    "for ops in range(len(result_async)):\n",
    "    \n",
    "    result_async1 = [pool1.apply_async(getRawHTML, args = (result_async[ops][index]['link'].strip(), )) for index in\n",
    "                    range(len(result_async[ops]))]\n",
    "    \n",
    "    result_async1 = [result_async1[id].get() for id in range(len(result_async1))]\n",
    "    process.append(result_async1)\n",
    "    #result_async1 = [result_async1[id].get() for id in range(len(result_async1))]\n",
    "    \n",
    "    #print(len(result_async))\n",
    "    \n",
    "    #for index in range(len(result_async[ops])):\n",
    "        \n",
    "        #rawFieldData = getRawHTML(result_async[ops][index]['link'].strip())\n",
    "        \n",
    "        #ulList = rawFieldData.find_all('ul')[2]\n",
    "        #requesthreflink = ((ulList.find('li')).find('a'))['href'][1:]\n",
    "        #data = rawFieldData.find_all('table')[0].find_all('tr')\n",
    "        \n",
    "        #arr = retrieveFieldData(requesthreflink)\n",
    "        \n",
    "        #rawFieldData = getRawHTML(result_async[ops][index]['link'].strip())\n",
    "        #ulList = rawFieldData.find_all('ul')[2]\n",
    "        #requesthreflink = ((ulList.find('li')).find('a'))['href'][1:]\n",
    "        #data = rawFieldData.find_all('table')[0].find_all('tr')\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e858d597",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 49/49 [01:23<00:00,  1.55s/it]\n"
     ]
    }
   ],
   "source": [
    "## FUNCTIONS\n",
    "def getRawHTML(link):\n",
    "    \n",
    "    r = get(link, headers={'User-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0'})\n",
    "    c = r.content\n",
    "    soup = BeautifulSoup(c, \"html.parser\")\n",
    "    \n",
    "    return soup\n",
    "\n",
    "def retrieveServiceData(data):\n",
    "    \n",
    "    all = data.find_all('table', {\"class\": \"typetable\"})\n",
    "    \n",
    "    serviceArr = []\n",
    "    for item in all[0].find_all('tr'):\n",
    "        serviceObj = {}\n",
    "        \n",
    "        try:\n",
    "            service = item.find_all('td')[0].find('a', {\"class\": \"link\"}).text\n",
    "            serviceObj['service'] = service\n",
    "        except:\n",
    "            service = 'NA'\n",
    "        \n",
    "        try:\n",
    "            desc = item.find_all('td')[1].text.replace(\"\\n\", \"\")\n",
    "            serviceObj['description'] = desc\n",
    "        except:\n",
    "            desc = 'NA'\n",
    "        \n",
    "        try:\n",
    "            postStr = item.find('a', {\"class\": 'link'})['href']\n",
    "            link = base_url + postStr\n",
    "            serviceObj['link'] = link\n",
    "        except:\n",
    "            link = 'NA'\n",
    "    \n",
    "        if serviceObj:\n",
    "            serviceArr.append(serviceObj)\n",
    "    \n",
    "    fileDir = dirPath +'/service'\n",
    "    if not path.exists(fileDir):\n",
    "        mkdir(fileDir)\n",
    "        \n",
    "    with open(path.join(fileDir, '') + 'service.json', 'w+') as outfile:\n",
    "        dump(serviceArr, outfile)\n",
    "        \n",
    "    return serviceArr\n",
    "\n",
    "def retrieveOperationData(data, index):\n",
    "    \n",
    "    all = data.find_all('table', {\"class\": \"typetable\"})\n",
    "\n",
    "    operationArr = []\n",
    "    for item in all[0].find_all('tr'):\n",
    "        operationOj = {}\n",
    "        \n",
    "        try:\n",
    "            ops = item.find_all('td')[0].find('a', {\"class\": \"link\"}).text\n",
    "            operationOj['operation'] = ops\n",
    "        except:\n",
    "            ops = 'NA'\n",
    "        \n",
    "        try:\n",
    "            desc = item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\u00a0\", \"\")\n",
    "            operationOj['description'] = desc\n",
    "        except:\n",
    "            desc = 'NA'\n",
    "        \n",
    "        try:\n",
    "            postStr = item.find('a', {\"class\": 'link'})['href']\n",
    "            link = base_url + serviceArr[index]['service'] + '/v38.2/' + postStr\n",
    "            link = link.strip()\n",
    "            operationOj['link'] = link\n",
    "        except:\n",
    "            link = 'NA'\n",
    "    \n",
    "        if operationOj:\n",
    "            operationOj['service'] = serviceArr[index]['service']\n",
    "            operationArr.append(operationOj)\n",
    "    \n",
    "    fileDir = dirPath +'/operation'\n",
    "    if not path.exists(fileDir):\n",
    "        mkdir(fileDir)\n",
    "        \n",
    "    individual_ops_target_dir = fileDir + '/'+ serviceArr[index]['service'] +'/'\n",
    "    if not path.exists(individual_ops_target_dir):\n",
    "        mkdir(individual_ops_target_dir)\n",
    "    \n",
    "    with open(path.join(individual_ops_target_dir, '') + serviceArr[index]['service'] + '.json', 'w+') as outfile:\n",
    "        dump(operationArr, outfile)\n",
    "    \n",
    "    return operationArr\n",
    "\n",
    "def retrieve(hrefName, data):\n",
    "    fieldsArr = []\n",
    "    for i in data:\n",
    "        for j in i.find_all('td'):\n",
    "            if j.find('a', {\"name\": hrefName}):\n",
    "                fieldsData = (j.find('table', {\"class\": 'typetable'})).find_all('tr')\n",
    "                for item in fieldsData:\n",
    "                    if len(item.find_all('td')) > 2:\n",
    "                        fieldsObj = {}\n",
    "                        try:\n",
    "                            fieldsObj['parameterName'] = item.find_all('td')[0].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['parameterName'] = 'NA'\n",
    "\n",
    "                        try:\n",
    "                            fieldsObj['type'] = item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                            if ((item.find_all('td')[1]).find('a')):\n",
    "                                if ((item.find_all('td')[1]).find('a')).get('href'): \n",
    "                                    fieldsObj[item.find_all('td')[1].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")] = retrieve(((item.find_all('td')[1]).find('a')).get('href')[1:], data)\n",
    "                        except:\n",
    "                            fieldsObj['type'] = 'NA'\n",
    "                            \n",
    "                        try:\n",
    "                            fieldsObj['cardinality'] = item.find_all('td')[2].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['cardinality'] = 'NA'\n",
    "    \n",
    "                        try:\n",
    "                            fieldsObj['description'] = item.find_all('td')[3].text.replace(\"\\n\", \"\").replace(\"\\xa0\", \"\")\n",
    "                        except:\n",
    "                            fieldsObj['description'] = 'NA'\n",
    "                            \n",
    "                        if fieldsObj:\n",
    "                            fieldsArr.append(fieldsObj)\n",
    "        \n",
    "    return fieldsArr\n",
    "\n",
    "def retrieveFieldData(link, service, operation):\n",
    "    \n",
    "    rawFieldData = getRawHTML(link)    \n",
    "    ulList = rawFieldData.find_all('ul')[2]\n",
    "    requesthreflink = ((ulList.find('li')).find('a'))['href'][1:]\n",
    "    data = rawFieldData.find_all('table')[0].find_all('tr')\n",
    "    xyz = retrieve(requesthreflink, data)\n",
    "\n",
    "    if service:\n",
    "        fileDir = dirPath +'/operation/' + service + '/fields'\n",
    "        if not path.exists(fileDir):\n",
    "            mkdir(fileDir)\n",
    "        \n",
    "        if operation:\n",
    "            with open(path.join(fileDir, '') + operation + \".json\", \"w+\") as outfile:\n",
    "                dump(xyz, outfile)\n",
    "        else:\n",
    "            print(\"NOT OPERATION\")\n",
    "    else:\n",
    "        print(\"NOT SERVICE\")\n",
    "    \n",
    "        \n",
    "    return True\n",
    "\n",
    "\n",
    "from requests import get\n",
    "from json import dump\n",
    "from os import getcwd\n",
    "from os import path\n",
    "from os import mkdir\n",
    "from tqdm import tqdm\n",
    "from bs4 import BeautifulSoup\n",
    "from multiprocessing import Pool, Process\n",
    "import threading\n",
    "\n",
    "dirPath = getcwd()\n",
    "\n",
    "base_url = \"https://community.workday.com/sites/default/files/file-hosting/productionapi/\"\n",
    "\n",
    "## Service Extraction\n",
    "rawServiceData = getRawHTML(\"https://community.workday.com/sites/default/files/file-hosting/productionapi/index.html\")\n",
    "serviceArr = retrieveServiceData(rawServiceData)\n",
    "pool=Pool(processes=5)\n",
    "process = []\n",
    "threads = []\n",
    "## Operations Extraction\n",
    "for index in tqdm(range(len(serviceArr))):\n",
    "    rawOperationData = getRawHTML(serviceArr[index]['link'].strip())\n",
    "    operationArr = retrieveOperationData(rawOperationData, index)\n",
    "    \n",
    "    ## Fields of Operation Extraction\n",
    "    for id in range(len(operationArr)):\n",
    "        #pool.apply_async(retrieveFieldData,(operationArr[id]['link'].strip(), operationArr[id]['service'], operationArr[id]['operation'],))\n",
    "        t = threading.Thread(target=retrieveFieldData, args=(operationArr[id]['link'].strip(), operationArr[id]['service'], operationArr[id]['operation'],))\n",
    "        #threads.append(t)\n",
    "        #t.start()\n",
    "        p=Process(target=retrieveFieldData,args=(operationArr[id]['link'].strip(), operationArr[id]['service'], operationArr[id]['operation'],))\n",
    "        process.append(p)\n",
    "        #p.start()\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6f0829b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 51%|█████     | 83/163 [13:11<13:15,  9.94s/it]  Process Process-3462:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3463:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3470:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3475:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3461:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3478:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3468:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3474:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3477:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3473:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3469:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3476:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 52%|█████▏    | 84/163 [13:25<14:38, 11.11s/it]Process Process-3472:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3471:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3485:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3479:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 52%|█████▏    | 85/163 [13:27<10:55,  8.41s/it]Process Process-3480:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3483:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3482:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3487:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3486:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3484:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Process Process-3488:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3496:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3490:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3491:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3494:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3492:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3498:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3495:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3497:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3481:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3493:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3489:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 53%|█████▎    | 86/163 [13:47<15:07, 11.78s/it]Process Process-3503:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Process Process-3501:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3507:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3506:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3508:\n",
      "Process Process-3500:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3504:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3502:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3505:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3499:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 53%|█████▎    | 87/163 [13:50<11:37,  9.17s/it]Process Process-3512:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3513:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3509:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 54%|█████▍    | 88/163 [13:52<08:45,  7.01s/it]Process Process-3511:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3516:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3517:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3518:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3514:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3510:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3520:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3521:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3523:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3527:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3526:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Process Process-3519:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "Process Process-3524:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 55%|█████▍    | 89/163 [13:55<07:06,  5.76s/it]FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3528:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3522:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3525:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3536:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3531:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3537:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3533:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3535:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3534:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3529:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 55%|█████▌    | 90/163 [13:58<06:08,  5.05s/it]Process Process-3532:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3515:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3530:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3542:\n",
      "Traceback (most recent call last):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3543:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3548:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3539:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 56%|█████▌    | 91/163 [14:01<05:15,  4.38s/it]Process Process-3544:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3545:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3538:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3541:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3549:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 56%|█████▋    | 92/163 [14:04<04:35,  3.88s/it]Process Process-3550:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3557:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3556:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3558:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3555:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3568:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3551:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3564:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3567:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3562:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3563:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Process Process-3561:\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3566:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3554:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3559:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 57%|█████▋    | 93/163 [14:08<04:41,  4.02s/it]Process Process-3560:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3572:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3573:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3577:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3575:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3578:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3576:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3570:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3574:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3565:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3569:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 58%|█████▊    | 94/163 [14:27<09:38,  8.38s/it]Process Process-3587:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3583:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3581:\n",
      "Process Process-3582:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3585:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3586:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3580:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3588:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3552:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process Process-3579:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 58%|█████▊    | 95/163 [14:43<12:08, 10.71s/it]Process Process-3546:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3547:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3589:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 59%|█████▉    | 96/163 [14:45<08:58,  8.04s/it]Process Process-3591:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3594:\n",
      "Process Process-3598:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3596:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3597:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3590:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3604:\n",
      "Process Process-3606:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3599:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Process Process-3600:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 60%|█████▉    | 97/163 [14:48<07:10,  6.52s/it]FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3592:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3607:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process Process-3603:\n",
      "Process Process-3605:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3608:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3601:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Traceback (most recent call last):\n",
      "Process Process-3602:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3611:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3610:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3609:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 60%|██████    | 98/163 [14:50<05:38,  5.21s/it]Process Process-3614:\n",
      "Traceback (most recent call last):\n",
      "Process Process-3616:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3618:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3615:\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3617:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process Process-3621:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3622:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3620:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3624:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Process Process-3619:\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      " 61%|██████    | 99/163 [14:53<04:50,  4.53s/it]Process Process-3627:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "Process Process-3628:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3625:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n",
      "Process Process-3623:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/purvang/anaconda3/lib/python3.8/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-70ef4189f725>\", line 142, in retrieveFieldData\n",
      "    mkdir(fileDir)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/purvang/project/py/python-projects/Applications/web-scrapper/operation/Human_Resources/fields'\n"
     ]
    }
   ],
   "source": [
    "step_size = 10\n",
    "initial = 0\n",
    "x = range(initial, len(process)-1000, step_size)\n",
    "for p in tqdm(range(initial, len(process)-1000, step_size)):\n",
    "    #print(range(step_size))\n",
    "    for step in range(initial, step_size):\n",
    "        #print(process[step])\n",
    "        process[step].start()\n",
    "    \n",
    "    initial = step_size\n",
    "    step_size = step_size + 10\n",
    "    process[p].join()\n",
    "\n",
    "print(\"demo\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f27d27d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "for x in threads:\n",
    "    print(x.isAlive())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5fe8413",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
